//! 构建脚本：把 `frontend/dist` 内嵌进二进制（决策 155）。
//!
//! dist 存在时逐文件拷入 OUT_DIR 并生成 `frontend_assets.rs`（`(dist 相对路径,
//! include_bytes!)` 表）；dist 缺失（如未装 Node 的环境直接 cargo build）时生成空表
//! ——构建不被前端绑架，axum 首页退化为「前端未构建」提示页（src/assets.rs）。

use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let dist = manifest_dir.join("../../frontend/dist");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", dist.display());

    let assets_dir = out_dir.join("frontend-dist");
    if assets_dir.exists() {
        fs::remove_dir_all(&assets_dir).expect("清理 OUT_DIR 内的旧资产");
    }

    let mut entries = Vec::new();
    for src in collect_files(&dist) {
        let rel = src
            .strip_prefix(&dist)
            .expect("文件应位于 dist 内")
            .to_string_lossy()
            .replace('\\', "/");
        let dest = assets_dir.join(&rel);
        fs::create_dir_all(dest.parent().expect("资产路径有父目录")).expect("建资产子目录");
        fs::copy(&src, &dest).unwrap_or_else(|e| panic!("拷贝 {} 失败：{e}", src.display()));
        println!("cargo:rerun-if-changed={}", src.display());
        entries.push(format!(
            "    ({rel:?}, include_bytes!({:?})),",
            dest.display()
        ));
    }

    let generated = format!(
        "// @generated by build.rs（决策 155）：frontend/dist → (dist 相对路径, 文件内容)。勿手改。\n\
         pub static EMBEDDED_ASSETS: &[(&str, &[u8])] = &[\n{}\n];\n",
        entries.join("\n")
    );
    fs::write(out_dir.join("frontend_assets.rs"), generated).expect("写生成资产表");
}

/// 递归收集 `dir` 下的普通文件（跳过点文件）；`dir` 不存在返回空。
/// 路径序遍历，保证生成物稳定。
fn collect_files(dir: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    let Ok(read) = fs::read_dir(dir) else {
        return out;
    };
    let mut entries: Vec<PathBuf> = read.filter_map(|e| e.ok()).map(|e| e.path()).collect();
    entries.sort();
    for path in entries {
        let name = path
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
            .into_owned();
        if name.starts_with('.') {
            continue;
        }
        if path.is_dir() {
            out.extend(collect_files(&path));
        } else if path.is_file() {
            out.push(path);
        }
    }
    out
}
